apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motion-backend-images-pvc
  namespace: default
spec:
  storageClassName: "MotionMainStorage" # ← 追加（PV側と一致させる）
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
